### ISSUE TITLE
Camera values save incorrectly

### ISSUE THREAD

**Issue by HalloweenPandas** [LazyBone152/XenoKit#8]
When editing the values in the camera modifiers tab and then saving them, they do not save correctly

Example:

### In XenoKit
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/1f771b1f-b37e-4fc6-8b95-f41ba846890c)

### In YaBAC Organizer
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/58ffc591-79c8-4c58-9ff0-be70864b61f4)

In this one the values for X/Z Disposition and Y/Z Disposition are broken and X and Y rotation are flipped.

And on another entry the same Disposition problem happens but now the Y and Z position have the same problem

### In XenoKit
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/d4f13fa4-85e1-4c1f-9b2c-3ecb2a043965)

### In YaBAC Organizer
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/c8deb13e-a38c-49ec-aaca-6bc53d5070a8)

**Comment by LazyBone152** [comment]
Those floats are just very small and that's why they appear like that. XenoKit wont show every digit of a number (otherwise you'd get numbers like 0.0000000007... not ideal) so they just appear as 0 on the UI, because that is basically what they are.

I'm guessing you were using the plus and minus buttons to get this result? I'm pretty sure typing 0 in directly should always make it absolutely 0. But either way there should be no difference in game.

Though I do think the camera modifier numbers should be slightly bigger. Just 0.00 is quite restricting.

**Comment by HalloweenPandas** [comment]
I did use the plus and minus buttons sometimes. But how come that I get values such as "7.45058e-10" when the value is 0 in XenoKit? Wouldn't the value in XenoKit be something like "7.45" if that were the case and not 0.00?

**Comment by LazyBone152** [comment]
XenoKit doesn't use any notation on float numbers when they get small like YaBAC seems to. It just shows the literal number, which in this case is too small to display so gets cut off and shown as 0.

I did just increase the possible size of the float numbers in commit 2e4f83021b1638c05210d942473b6b0fd82efd6d, but it still wouldn't be able to show those numbers as anything other than 0 (you would need like ten digits)

**Comment by LazyBone152** [comment]
I forgot to mention that the rotation XY order was also fixed in that commit.
